# Generated by Django 2.2 on 2021-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210301_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('1', 'Red'), ('2', 'Green'), ('3', 'Blue'), ('4', 'White'), ('5', 'Black'), ('6', 'Other')], max_length=10),
        ),
    ]
