# Generated by Django 2.2 on 2021-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+996770124356', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
